spring:
  application:
    name: usuario-service
  cloud:
    config:
      uri: http://localhost:8585
      username: root
      password: s3cr3t
  boot:
    admin:
      client:
        url: http://localhost:8086