server:
  port: 8585

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IVANMAMANI2003/DEVA_MICROSERVICIOS_BK.git
          searchPaths: config-data
          username: IVANMAMANI2003
          password: mamanigit123
          default-label: main
  security:
    user:
      name: root
      password: s3cr3t
